### ISSUE TITLE
Button color not working

### ISSUE THREAD

**Issue by tonmoy998** [freakmangd/Simple-Button#3]
_G.love = require("love")

local ButtonManager = require("simplebutton")

local screen = { w = love.graphics.getWidth(), h = love.graphics.getHeight() }

function love.load()
	whale = love.graphics.newImage("whale.png")
	showImage = ButtonManager.new("Show", screen.w / 2 - 50, screen.h / 2 - 20, 100, 40,false,{24,78,20,1})
	showImage:setAlignment("center")
end

function love.draw()

	if showImage.value == true then
		love.graphics.draw(whale)
	end
  
  ButtonManager.draw()
end

function love.mousepressed(x, y, msbutton, istouch, presses)
	ButtonManager.mousepressed(x, y, msbutton)
end

function love.mousereleased(x, y, msbutton, istouch, presses)
	ButtonManager.mousereleased(x, y, msbutton)
end

**Comment by freakmangd** [comment]
Love uses a floating point number between 0 and 1 for its colors. if you do something like this:
`{24/255,78/255,20/255,1}` 
the color will come out correctly

**Comment by tonmoy998** [comment]
Thanks for your response
